### ISSUE TITLE
本番環境DB(slave)での実験方法

### ISSUE THREAD

**Issue by noriyuki-togashi** [noriyuki-togashi/test#80]
スレーブでの作業の手順
- 本当にそこがスレーブかどうか確認する
```
mysql> show slave status\G
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: 10.32.26.116
                  Master_User: repl
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: bin.000177
          Read_Master_Log_Pos: 391150088
               Relay_Log_File: relay.000334
                Relay_Log_Pos: 391150228
        Relay_Master_Log_File: bin.000177
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
```

本番DBのコピーを使った実験方法 - Sakura - Confluence https://confl2.drecom.jp/pages/viewpage.action?pageId=599000078
