### ISSUE TITLE
m17n_text翻訳対応

### ISSUE THREAD

**Issue by noriyuki-togashi** [noriyuki-togashi/test#84]
## 翻訳するカラムを指定
```
# モジュールのインクルード
include ::Concerns::M17nTextModule
# 翻訳するカラムを指定する
m17n_column_for :name
```

## 翻訳シート出しの手順
- define.rbに以下をテーブル名、カラム名、翻訳シート名設定する
例：
```
base_id_table:
  characters: 1
base_id_column:
  name: 1
sheet_name:
  characters.name: chara_name
```
- 翻訳シートを出す
```
bundle exec rake m17n:dmaster:generate_sheet INPUT=../sakura-master-data/master_excel/yozakura_release/score_event_2.xlsx
```
